### ISSUE TITLE
Argument of type '"save"' is not assignable to parameter of type 'Hook'.

### ISSUE THREAD

**Issue by inoui** [GrapeoffJS/kindagoose#87]
I ve tried your example of Event tracking but I have a TS error :
Argument of type '"save"' is not assignable to parameter of type 'Hook'.

I think your hook should be :

`export type Hook = MongooseQueryMiddleware | MongooseQueryMiddleware[] | MongooseDocumentMiddleware | MongooseDocumentMiddleware[] | RegExp;
`

**Comment by GrapeoffJS** [comment]
Sorry, haven't checked my GitHub for a long time, was immersed into work... I will handle this today/tomorrow.

**Comment by GrapeoffJS** [comment]
I created a [branch](https://github.com/GrapeoffJS/kindagoose/tree/fix-hooks-typings) with a bunch of fixes, but can't test them now because of other tasks for today. I'll be able to check it only tomorrow, but if you can test it now, I will publish a new version today.

P.S. `peerDependencies` have some changes.

```json
    "peerDependencies": {
        "@nestjs/common": "^9.2.1",
        "@nestjs/core": "^9.3.9",
        "@typegoose/typegoose": "^10.3.0",
        "mongoose": "^7.0.0",
        "reflect-metadata": "^0.1.13",
        "rxjs": "^7.5.6 || <9.0.0"
    }
```

@nestjs/core must be 9.3.9 or later, @typegoose/typegoose must be 10.3.0 or later and mongoose must be 7.0.0 or later.

**Comment by GrapeoffJS** [comment]
https://github.com/GrapeoffJS/kindagoose/releases/tag/1.3.1

https://www.npmjs.com/package/kindagoose
